### ISSUE TITLE
Como usuario debo poder listar productos y hacer login de ser necesario sin pasar por el login

### ISSUE THREAD

**Issue by belluccifranco** [globo-technology/sic-com#28]
- [x] Cambiar el routing para que no pase por el login
- [x] Al estar sin token el menu solo debe mostrar la opcion "Iniciar sesion"
- [x] Al estar sin token, en la vista de detalle producto, no se debe mostrar el input y los botones para agregar al carrito
- [x] El form de login debe ser dialog modal

**Comment by facundososalopez** [comment]
Hay que quitar la seguridad para los siguientes endpoints:
/carrito-compra/usuarios/null/cantidad-renglones
/productos/busqueda/criteria?idEmpresa=1&descripcion=&pagina=0&tamanio=10&publicos=true

**Comment by belluccifranco** [comment]
Ya estan creados los 2 endpoints necesarios para recuperar los productos y un producto individual:
GET /public/productos/busqueda/criteria
GET /public/productos/{idProducto}

**Comment by belluccifranco** [comment]
- [ ] No funciona el "enter" en la vista de login para disparar el submit
- [ ] El label del boton "Aceptar" debe decir "Ingresar"
- [ ] Quitar el boton "Cancelar" y agregar otro DEBAJO con label "Registrarme" con color warn (el opuesto al principal). El dialog se deberia cerrar al clickear afuera o presionando ESC
- [ ] El link de "Olvide mi contrasenia deberia estar debajo del input de password
- [ ] Al darle al boton "Registrarme" debe cerrar el dialog de login y abrir el nuevo dialog de registracion (otro ticket)
- [ ] Al darle al LINK "Olvide mi contrasenia" debe cerrar el dialog de login y abrir el nuevo dialog de recupero de password
- [ ] Luego de hacer login, no carga el nombre de usuario en el menu
